version: "3"

services:
  backend: 
    container_name: BACKEND_API
    image: backend:latest
    build: ./backend
    restart: unless-stopped
    ports:
      - "5000:5000" 

  frontend:
    container_name: FRONTEND
    image: frontend:latest
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
